### ISSUE TITLE
Makefile + Dockerfile

### ISSUE THREAD

**Issue by cansurmeli** [se2p/ps-2019-assignment-03-public-tests#2]
Hello.

As we've discussed on Stud.IP previously, I've constructed Makefile and Dockerfile(has `make` and other necessary stuff for the Docker instance to automatically test the tasks with the Makefile).

As the Makefile and Dockerfile are task related, it doesn't make sense for me to make a pull-request to the `public-tests` repo. Dr. Gambi has the files and will integrate them accordingly.

**Comment by alessiogambi** [comment]
@cansurmeli Thanks for your contribution. I will integrate make and docker as soon as possible.
